version: '3.8'

services:
  backend:
    build: ./backend
    container_name: leaderboard-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/leaderboard
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: leaderboard-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: leaderboard-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: leaderboard
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: leaderboard-redis
    ports:
      - "6379:6379"

volumes:
  db-data:
